services:
  gpu_train:
    build:
      dockerfile: services/gpu_train/Dockerfile
      context: .
    shm_size: "30gb"
    environment:
      - PYTHONPATH=/workspace
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]
              driver: nvidia
    volumes:
      - .:/workspace
  
  cpu_train:
    build:
      dockerfile: services/cpu_train/Dockerfile
      context: .
    shm_size: "30gb"
    environment:
      - PYTHONPATH=/workspace
    volumes:
      - .:/workspace
    